language: go

addons:
  apt:
    packages:
    - sshpass

env:
  global:
    - GIN_MODE=release
    - GOOS=linux
    - GOARCH=amd64
go:
- 1.14.x

script:
  - go build main.go

after_success:
  - "sshpass -p $TARGET_PASS scp ./main $TARGET"